language: node_js
node_js:
- "12.16.1"

branches:
  only:
 - master

before_script:
- npm install -g --silent firebase-tools
- npm install -g --silent @angular/cli

script:
- ng build --prod --aot
- firebase deploy --token $FIREBASE_TOKEN

after_success:
- firebase deploy --token $FIREBASE_TOKEN
