language: node_js
node_js:
- node # latest node

branches:
  only:
 - master

before_script:
- npm install -g firebase-tools
- npm install -g @angular/cli

script:
- ng build --prod --aot
- firebase deploy --token $FIREBASE_TOKEN

after_success:
- firebase deploy --token $FIREBASE_TOKEN
